version: '3.8'

services:
  deno-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      SPIN_VARIABLE_RAIL_API_KEY: "${SPIN_VARIABLE_RAIL_API_KEY}"
      SPIN_VARIABLE_OPEN_WEATHER_API_KEY: "${SPIN_VARIABLE_OPEN_WEATHER_API_KEY}"
      SPIN_VARIABLE_MET_OFFICE_API_KEY: "${SPIN_VARIABLE_MET_OFFICE_API_KEY}"
